### ISSUE TITLE
RR7 version?

### ISSUE THREAD

**Issue by JasonColeyNZ** [moishinetzer/remix-live-loader#7]
Hi there,

First off this is a great example for sse on remix.

Secondly do you have an example that will work successfully with RR7? I have all sorts of issues trying to get this working successfully with RR7, trying to port an app over to RR7 now, but the sse isn't working as expected. I have having the app freeze during page navigations (especially if I have two tabs each with the same page open). The controllers are not closing correctly when the page is closed. I'm a bit new to this so not sure where to start, I am however working on porting your example over to RR7 to see if this has the same issues.

Regards
Jason

**Comment by JasonColeyNZ** [comment]
this is one error I am getting while updating your repo to rr7

TypeError: Invalid state: Controller is already closed
    at ReadableStreamDefaultController.enqueue (node:internal/webstreams/readablestream:1077:13)
    at send (file:///Users/imac27/Repos/remix-live-loader/node_modules/remix-utils/build/server/event-stream.js:12:28)
    at EventEmitter.handle (/Users/imac27/Repos/remix-live-loader/app/utils/create-event-stream.server.ts:7:7)
    at EventEmitter.emit (node:events:530:35)
    at EventEmitter.emit (node:domain:489:12)
    at action (/Users/imac27/Repos/remix-live-loader/app/routes/todos/$listSlug/index.tsx:23:10)
    at callRouteHandler (/Users/imac27/Repos/remix-live-loader/node_modules/react-router/dist/development/index.js:8630:16)
    at /Users/imac27/Repos/remix-live-loader/node_modules/react-router/dist/development/index.js:3543:19
    at callLoaderOrAction (/Users/imac27/Repos/remix-live-loader/node_modules/react-router/dist/development/index.js:3593:16)
    at async Promise.all (index 2)
    at /Users/imac27/Repos/remix-live-loader/node_modules/react-router/dist/development/index.js:8868:19
    at callDataStrategyImpl (/Users/imac27/Repos/remix-live-loader/node_modules/react-router/dist/development/index.js:3503:17)
    at callDataStrategy (/Users/imac27/Repos/remix-live-loader/node_modules/react-router/dist/development/index.js:3023:19)
    at submit (/Users/imac27/Repos/remix-live-loader/node_modules/react-router/dist/development/index.js:2881:21)
    at queryImpl (/Users/imac27/Repos/remix-live-loader/node_modules/react-router/dist/development/index.js:2828:23)
    at Object.query (/Users/imac27/Repos/remix-live-loader/node_modules/react-router/dist/development/index.js:2760:18)
    at singleFetchAction (/Users/imac27/Repos/remix-live-loader/node_modules/react-router/dist/development/index.js:8886:18)
    at handleSingleFetchRequest (/Users/imac27/Repos/remix-live-loader/node_modules/react-router/dist/development/index.js:9261:64)
    at requestHandler (/Users/imac27/Repos/remix-live-loader/node_modules/react-router/dist/development/index.js:9164:18)
    at dispatch (file:///Users/imac27/Repos/remix-live-loader/node_modules/hono/dist/compose.js:30:17)
    at file:///Users/imac27/Repos/remix-live-loader/node_modules/remix-hono/build/i18next.js:14:9
    at dispatch (file:///Users/imac27/Repos/remix-live-loader/node_modules/hono/dist/compose.js:30:17)
    at dispatch (file:///Users/imac27/Repos/remix-live-loader/node_modules/hono/dist/compose.js:30:17)
    at dispatch (file:///Users/imac27/Repos/remix-live-loader/node_modules/hono/dist/compose.js:30:17)
    at file:///Users/imac27/Repos/remix-live-loader/node_modules/hono/dist/hono-base.js:195:25
    at getRequestListener.overrideGlobalObjects (file:///Users/imac27/Repos/remix-live-loader/node_modules/@hono/vite-dev-server/dist/dev-server.js:93:32)
    at responseViaResponseObject (file:///Users/imac27/Repos/remix-live-loader/node_modules/@hono/node-server/dist/index.mjs:333:15)

**Comment by JasonColeyNZ** [comment]
It doesn't happen immediately, you have to have a couple of tabs open, navigate back and forth between them and select/deselect a few tasks and it eventually comes up

**Comment by JasonColeyNZ** [comment]
OK, it appears to be something with Hono server that is causing this, I was using the reactRouterHonoServer(), something is happening here with the emitter, i shall keep looking

**Comment by moishinetzer** [comment]
Hi Jason, 

It seems that this is Hono/Build speicific to your project and not the implementation/concept of this repo itself so I'm going to close this issue for now.

If you can replicate this in the basic RR7 template feel free to ping here with a repro and I'll reopen this issue. (I don't personally think the RR7 template is production ready just yet either to be honest with you)

**Comment by JasonColeyNZ** [comment]
Here is a repro using the hono server.
https://github.com/JasonColeyNZ/remix-live-loader
